# Generated by Django 4.1.1 on 2023-01-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, null=True)),
                ('description', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificSubheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Specific subheading', max_length=150)),
                ('superior_heading', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='content.domain')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Enter Content here', max_length=10000)),
                ('superior_subheading', models.ForeignKey(default='what subheading am i under', on_delete=django.db.models.deletion.CASCADE, to='content.specificsubheading')),
            ],
        ),
        migrations.CreateModel(
            name='CommonSubheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='common subheading', max_length=150)),
                ('Domain', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='content.domain')),
            ],
        ),
        migrations.CreateModel(
            name='CommonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Enter Content here', max_length=10000)),
                ('superior_subheading', models.ForeignKey(default='what subheading am i under', on_delete=django.db.models.deletion.CASCADE, to='content.commonsubheading')),
            ],
        ),
    ]
