# Generated by Django 4.1.1 on 2023-02-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='common subheading', max_length=150)),
                ('content', models.TextField(default='content for this subheading', max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='commonsubheading',
            name='Domain',
        ),
        migrations.RemoveField(
            model_name='specificcontent',
            name='superior_subheading',
        ),
        migrations.RemoveField(
            model_name='specificsubheading',
            name='superior_heading',
        ),
        migrations.AddField(
            model_name='domain',
            name='body_Plan',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='domain',
            name='cell_type',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='domain',
            name='characteristics',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='domain',
            name='circulatory',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='domain',
            name='divergent_event',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='domain',
            name='examples',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='domain',
            name='metabolism',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='domain',
            name='reproduction',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='domain',
            name='respiratory',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='domain',
            name='vocabulary',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.DeleteModel(
            name='CommonContent',
        ),
        migrations.DeleteModel(
            name='CommonSubheading',
        ),
        migrations.DeleteModel(
            name='SpecificContent',
        ),
        migrations.DeleteModel(
            name='SpecificSubheading',
        ),
        migrations.AddField(
            model_name='subheading',
            name='Domain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='content.domain'),
        ),
    ]
