# Generated by Django 4.1.1 on 2023-02-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_subheading_remove_commonsubheading_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='body_Plan',
            new_name='body_plan',
        ),
    ]
