# Generated by Django 4.1.1 on 2023-02-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_body_plan_domain_body_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='keytraits',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
