# Generated by Django 4.1.1 on 2023-02-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_domain_keytraits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='keytraits',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
